source 'http://rubygems.org'

gem 'rake', '~> 10.4.2'
gem 'nanoc', '~> 3.7.4'
gem 'guard-nanoc', '~> 1.0.3'

gem 'sass', '~> 3.4.9'
gem 'sass-css-importer', '~> 1.0.0.beta.0'
gem 'redcarpet', '~> 3.2.2'
gem 'rouge', '~> 1.7.4'
gem 'sprockets', '~> 2.12.3'
# gem 'nanoc-sprockets3', '~> 1.0.2'
gem 'uglifier', '~> 2.7.0'
gem 'pry', '~> 0.10.1'
gem 'pry-stack_explorer', '~> 0.4.9.2'

gem 'stringex'
gem 'nokogiri'
gem 'haml'
gem 'rainpress'
gem 'kramdown'
gem 'systemu'
gem 'asdf'
gem 'mime-types'
